### ISSUE TITLE
ActiveRecord::AssociationTypeMismatch in Admin/stylesController#new

### ISSUE THREAD

**Issue by ghost** [radiant/radiant-sheets-extension#6]
trace from trying to create a new style; scripts give a similar error.

```
ActiveRecord::AssociationTypeMismatch in Admin/stylesController#new

User(#2181969380) expected, got User(#2177102540)

/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations/association_proxy.rb:259:in `raise_on_type_mismatch'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations/belongs_to_association.rb:22:in `replace'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/associations.rb:1287:in `created_by='
/tmp/rad/vendor/radiant/app/models/user_action_observer.rb:19:in `before_create'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/observer.rb:171:in `send'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/observer.rb:171:in `update'
/Volumes/users/john/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/observer.rb:185:in `notify_observers'
/Volumes/users/john/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/observer.rb:184:in `each'
/Volumes/users/john/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/observer.rb:184:in `notify_observers'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:357:in `notify'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:350:in `callback'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:265:in `create'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/base.rb:2927:in `create_or_update_without_callbacks'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/callbacks.rb:250:in `create_or_update'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/base.rb:2577:in `save_without_validation'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/validations.rb:1090:in `save_without_dirty'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/dirty.rb:79:in `save_without_transactions'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:229:in `send'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:182:in `transaction'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/tmp/rad/vendor/radiant/vendor/rails/activerecord/lib/active_record/transactions.rb:196:in `save'
/tmp/rad/vendor/radiant/vendor/extensions/sheets/app/controllers/admin/sheet_resource_controller.rb:51:in `create_root'
/tmp/rad/vendor/radiant/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `send'
/tmp/rad/vendor/radiant/vendor/rails/activesupport/lib/active_support/callbacks.rb:178:in `evaluate_method'
/tmp/rad/vendor/radiant/vendor/rails/activesupport/lib/active_support/callbacks.rb:166:in `call'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:225:in `call'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:629:in `run_before_filters'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:615:in `call_filters'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/tmp/rad/vendor/radiant/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/Volumes/users/john/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/tmp/rad/vendor/radiant/vendor/rails/activesupport/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/flash.rb:151:in `perform_action'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/base.rb:532:in `send'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/base.rb:532:in `process_without_filters'
/tmp/rad/vendor/radiant/vendor/rails/actionpack/lib/action_controller/filters.rb:606:in `process_without_compass'
/Volumes/users/john/.rvm/gems/ree-1.8.7-2011.03@tmprad/gems/compass-0.10.6/lib/compass/app_integration/rails/actionpack2/action_controller.rb:7:in `process'
```

**Comment by ghost** [comment]
ugh. as far as i can tell all the problems were caused by pow...

**Comment by jomz** [comment]
I just experienced this as well but on webrick. It went away after I uploaded a stylesheet..

**Comment by will-r** [comment]
I'm still seeing this with rc3. It only happens during root page creation.

```

/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/associations/association_proxy.rb:259:in `raise_on_type_mismatch'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/associations/belongs_to_association.rb:22:in `replace'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/associations.rb:1287:in `created_by='
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/radiant-1.0.0.rc3/app/models/user_action_observer.rb:19:in `before_create'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/observer.rb:171:in `send'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/observer.rb:171:in `update'
/Users/will/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/observer.rb:185:in `notify_observers'
/Users/will/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/observer.rb:184:in `each'
/Users/will/.rvm/rubies/ruby-1.8.7-p352/lib/ruby/1.8/observer.rb:184:in `notify_observers'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/callbacks.rb:357:in `notify'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/callbacks.rb:350:in `callback'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/callbacks.rb:265:in `create'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/base.rb:2927:in `create_or_update_without_callbacks'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/callbacks.rb:250:in `create_or_update'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/base.rb:2577:in `save_without_validation'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/validations.rb:1089:in `save_without_dirty'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/dirty.rb:79:in `save_without_transactions'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/transactions.rb:229:in `send'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/transactions.rb:229:in `with_transaction_returning_status'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/transactions.rb:182:in `transaction'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/transactions.rb:228:in `with_transaction_returning_status'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/transactions.rb:196:in `save'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/transactions.rb:208:in `rollback_active_record_state!'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activerecord-2.3.14/lib/active_record/transactions.rb:196:in `save'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/radiant-sheets-extension-1.0.2/app/models/sheet.rb:23:in `create_root'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/radiant-sheets-extension-1.0.2/app/controllers/admin/sheet_resource_controller.rb:44:in `create_root'
/Users/will/.rvm/gems/ruby-1.8.7-p352@radiantrc3/gems/activesupport-2.3.14/lib/active_support/callbacks.rb:178:in `send'
```

**Comment by gommo** [comment]
I too have run into this on a new install of rc3.
